version: '3'
services:
  homeassistant:
    image: "homeassistant/home-assistant:latest"
    container_name: homeassistant
    environment:
      - TZ=Europe/Oslo
    volumes:
      - ~/Projects/home-server/mnt/home-assistant-data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    ports:
      - 8123:8123

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Oslo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/Projects/home-server/mnt/portainer-data:/data
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443

  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=Europe/Oslo
      - PUID=501
      - PGID=12
    restart: always
    volumes:
      - ~/Projects/home-server/mnt/heimdall-data:/config
    ports:
      - 7888:80
      - 4443:443
